### PR TITLE
Update GRDB.swift hash to build against 4.2

### PR DESCRIPTION
**Pull request by clackary**
### Pull Request Description

Updates the hash to a recent commit, and also updates the configuration to build against Swift 4.2. Also removes the xfail from https://bugs.swift.org/browse/SR-8234. 

### Acceptance Criteria
- [x] pass `./project_precommit_check` script run
```
./project_precommit_check GRDB.swift --earliest-compatible-swift-version 4.2
** CHECK **
--- Validating GRDB.swift Swift version 4.2 compatibility ---
--- Project configured to be compatible with Swift 4.2 ---
--- Checking GRDB.swift platform compatibility with Darwin ---
--- Platform compatibility check succeeded ---
--- Locating swiftc executable ---
$ xcrun -f swiftc
--- Checking installed Swift version ---
$ /Applications/Xcodes/Xcode_10_Beta_6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
--- Version check succeeded ---
--- Executing build actions ---
$ ./runner.py --swift-branch swift-4.2-branch --swiftc /Applications/Xcodes/Xcode_10_Beta_6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --projects projects.json --include-repos 'path == "GRDB.swift"' --include-versions 'version == "4.2"' --include-actions 'action.startswith("Build")'
PASS: GRDB.swift, 4.2, 0e0ebd, Swift Package
========================================
Action Summary:
     Passed: 1
     Failed: 0
    XFailed: 0
    UPassed: 0
      Total: 1
========================================
Repository Summary:
      Total: 1
========================================
Result: PASS
========================================
--- GRDB.swift checked successfully against Swift 4.2 ---
```

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
Closing, as top of tree on GRDB.swift master branch still exhibits the issue.

**Comment by groue** [comment]
Hello. Should I update GRDB manifest file?

**Comment by clackary** [comment]
@groue The GRDB manifest should be fine. It's the manifest of the CSQLite.swift dependency that is causing trouble. See [CSQLite.swift's manifest].(https://github.com/groue/CSQLite/blob/51210b121508dd91dcced13d398269c004b0f1b5/Package.swift#L6)
```
https://github.com/groue/CSQLite.git @ 0.2.0: error: manifest parse error(s):
/var/folders/zr/mvb5rn8j4sx9vynr3cb1h8wh0000gp/T/TemporaryFile.h2PaNw.swift:6:10: error: type 'SystemPackageProvider' has no member 'Apt'; did you mean 'apt'?
        .Apt("libsqlite3-dev")
         ^~~
         apt
PackageDescription.SystemPackageProvider:5:24: note: 'apt' declared here
    public static func apt(_ packages: [String]) -> PackageDescription.SystemPackageProvider
                       ^
```

Also, I tried reaching out to the maintainer email address we have for GRDB.swift. Is `gwendal.roue@gmail.com` still the best address to use when necessary?

**Comment by groue** [comment]
Yes it is the correct email address. I missed your email, apparently: apologies.

So I have to update CSQLite.swift, right?

This package is very old. SPM has evolved a lot since. And my knowledge is lagging behind.

My only constraint is that the GRDB package can still be built on Linux (there aren't much users, but they are important to me). Do you have a recommendation, besides upgrading CSQLite/Package.swift to the latest SPM API?

**Comment by groue** [comment]
Thanks @clackary for the hint. Please give me a few days, until I get able to make the necessary tests ("just" build GRDB on a Linux box).

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@groue Thanks! It looks like this has uncovered a compiler crash. Since it builds with 4.2, I've filed [SR-9151](https://bugs.swift.org/browse/SR-9151) to be investigated.
