### PR TITLE
Add ReactiveKit

### PR DESCRIPTION
**Pull request by tonyarnold**
### Pull Request Description

Adds [ReactiveKit](https://github.com/DeclarativeHub/ReactiveKit). 

This PR supersedes #325.

### Acceptance Criteria

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [ ] maintain a project branch that builds against Swift 4.0 and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass `./project_precommit_check` script run

### Notes

I wasn't sure which iOS Simulator device to use - I've chosen an iPhone 11. Please let me know if this isn't suitable.

### CODE REVIEW

**Comment by clackary** [comment]
@swift-ci test

**Comment by tonyarnold** [comment]
It's failed - my apologies, @clackary. What version of Swift is being used for the compatibility suite right now? That's the failure I'm seeing when trying to build the project with Swift 5.2 snapshots.

**Comment by clackary** [comment]
It looks like we have Xcode 11.3 (11C29) installed on ci.swift.org.

```
$ swiftc -version
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
```

**Comment by tonyarnold** [comment]
After talking to @srdanrasic, I've removed Bond from this - the library we have the most trouble with across Swift releases and breakage has been ReactiveKit, and that works on it's own under Swift 5.1.

Bond is a story for another day.

**Comment by tonyarnold** [comment]
Do the Swift CI test runs need to be initiated by authorised  users, or can anyone start them?

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@tonyarnold Yes, it requires certain permissions to kick off tests. Feel free to ping me with a mention when a PR is ready for testing.

**Comment by clackary** [comment]
You can see the ReactiveKit failures [here](https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/553/artifact/swift-source-compat-suite/).

```
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/ReactiveKit/Sources/Connectable.swift:125:93: error: 'Self.LoadingValue' requires the types 'Self.Error' and 'Never' be equivalent
    public func replayValues(limit: Int = Int.max) -> ConnectableSignal<Signal<LoadingState<LoadingValue, LoadingError>, Error>> {
                                                                                            ^
```

Are you seeing something similar when building with Xcode 11.3?

**Comment by tonyarnold** [comment]
No, it's only just started happening in 5.2 - I filed a bug, and have had some feedback there: https://bugs.swift.org/browse/SR-12026

I'll update our git hash to point to a "fixed" version of ReactiveKit to get this into the compatibility suite so that we don't have to do this dance again in future 😉

**Comment by tonyarnold** [comment]
Ok, this PR is now proposing the commit hash for [ReactiveKit 3.16.1](https://github.com/DeclarativeHub/ReactiveKit/releases/tag/v3.16.1), which includes a fix for the Swift 5.2 issue identified by CI. Would you mind testing it again, and see if it passes? Thank you!

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
Thanks @tonyarnold!

**Comment by tonyarnold** [comment]
Thanks for your patience, @clackary :grinning:
