### PR TITLE
Add SwiftLint

### PR DESCRIPTION
**Pull request by jpsim**
### Pull Request Description

[SwiftLint](https://github.com/realm/SwiftLint) is a linter & formatter, used to enforce Swift style and usage conventions.

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 3.0 compatibility mode
      and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass ./check script run

### CODE REVIEW

**Comment by lplarson** [comment]
Looks good. Thanks!

**Comment by jpsim** [comment]
Out of curiosity, is it preferable to keep adapt _our projects_ to fix compilation issues with Swift 3.0, or is it better to keep those compilation issues so that they're highlighted by testing the compatibility suite?

For example, the latest version of SwiftLint that compiles with Swift 3.1 (Xcode 8.3.2) fails when compiled with Swift 3.0:

```
Compile Swift Module 'Yams' (13 sources)
~/SwiftLint/Packages/Yams-0.3.2/Sources/Yams/Emitter.swift:320:13: error: value of type 'ContiguousArray<CChar>' (aka 'ContiguousArray<Int8>') has no member 'withUnsafeMutableBytes'
        _ = value.withUnsafeMutableBytes { value in
            ^~~~~ ~~~~~~~~~~~~~~~~~~~~~~
~/SwiftLint/Packages/Yams-0.3.2/Sources/Yams/Emitter.swift:342:13: error: value of type 'ContiguousArray<CChar>' (aka 'ContiguousArray<Int8>') has no member 'withUnsafeMutableBytes'
        _ = tag.withUnsafeMutableBytes { tag in
            ^~~ ~~~~~~~~~~~~~~~~~~~~~~
~/SwiftLint/Packages/Yams-0.3.2/Sources/Yams/Emitter.swift:363:13: error: value of type 'ContiguousArray<CChar>' (aka 'ContiguousArray<Int8>') has no member 'withUnsafeMutableBytes'
        _ = tag.withUnsafeMutableBytes { tag in
            ^~~ ~~~~~~~~~~~~~~~~~~~~~~
```

I could easily adapt this code to compile successfully with both Swift 3.1 _and_ Swift 3.0, but I don't know if I'd be _helping_ or _hurting_ this project's intended purpose 😅 

Thanks for doing this! 👍

**Comment by lplarson** [comment]
Since this is a new API that didn't exist in 3.0 and is expected to break compatibility, I wouldn't worry about changing it.

**Comment by lplarson** [comment]
I'll change the version information in projects.json.

**Comment by lplarson** [comment]
Nevermind, you used an older commit that is compatible with 3.0. This is a good candidate to have both a 3.0 commit and a 3.1 commit. Would you be willing to add a more recent 3.1 commit in a new pull request?

**Comment by jpsim** [comment]
Thanks for the info! A new commit to test with Swift 3.1 has been added in #17.
