### PR TITLE
Fix a Python exception that occurred while running the SourceKit stress tester

### PR DESCRIPTION
**Pull request by ahoppen**
For reasons I don’t fully understand `subbuilder_result` can be `None`, so we can’t assign the `logfile` property here. This caused the stress tester to fail with the following error: (https://ci.swift.org/job/swift-main-sourcekitd-stress-tester/191/console)
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/ec2-user/jenkins/workspace/swift-main-sourcekitd-stress-tester/swift-source-compat-suite/project.py", line 1052, in start_process
    return project_subbuilder.build()
  File "/Users/ec2-user/jenkins/workspace/swift-main-sourcekitd-stress-tester/swift-source-compat-suite/project.py", line 1008, in build
    subbuilder_result = self.subbuilder.initialize(*([subtarget] + self.payload())).build(
  File "/Users/ec2-user/jenkins/workspace/swift-main-sourcekitd-stress-tester/swift-source-compat-suite/project.py", line 1011, in build
    subbuilder_result.logfile = log_filename
AttributeError: 'NoneType' object has no attribute 'logfile'
```

I’m just adding an `if` here to work around the crash to get the stress tester passing, there might be a more fundamental fix, but I don’t think I’ve got the capacity right now to chase it down.

Caused by https://github.com/apple/swift-source-compat-suite/pull/705

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by justice-adams-apple** [comment]
So apparently results objects can be `None` in certain cases. I did not realize this, and assumed they would all be valid objects (thus the error). This is due to the use of `--only-latest-versions`.  The script is determining if a currently listed version is the latest, and if not, returning `None`. It feels weird to be returning `None` for a build result rather than just filtering out said build altogether, but I'll handle that another time.
```python3
        if self.only_latest_versions:
            if self.version['version'] != \
               sorted(self.project['compatibility'],
                      reverse=True,
                      key=lambda x: [float(y) for y in x['version'].split('.')])[0]['version']:
                return None
```

In any case, this should fix things so thanks 👍 . I'll make a small patch to the Junit functionality so it can account for build results which are `None` as well since I didn't realize that was possible.

LGTM

**Review by justice-adams-apple — APPROVED** [review]
