### PR TITLE
[Add] PlanGrid/ReactiveLists

### PR DESCRIPTION
**Pull request by jessesquires**
### Pull Request Description

Adds [ReactiveLists](https://github.com/plangrid/ReactiveLists) to the suite, which is used in the PlanGrid iOS app.

### Acceptance Criteria

To be accepted into the Swift source compatibility test suite, a project must:

- [x] be an *Xcode* or *swift package manager* project
- [x] support building on either Linux or macOS
- [x] target Linux, macOS, or iOS/tvOS/watchOS device
- [x] be contained in a publicly accessible git repository
- [x] maintain a project branch that builds against Swift 4.0 and passes any unit tests
- [x] have maintainers who will commit to resolve issues in a timely manner
- [x] be compatible with the latest GM/Beta versions of *Xcode* and *swiftpm*
- [x] add value not already included in the suite
- [x] be licensed with one of the following permissive licenses:
	* BSD
	* MIT
	* Apache License, version 2.0
	* Eclipse Public License
	* Mozilla Public License (MPL) 1.1
	* MPL 2.0
	* CDDL
- [x] pass `./project_precommit_check` script run

Ensure project meets all listed requirements before submitting a pull request.

### CODE REVIEW

**Comment by clackary** [comment]
Quick update: looks like this might be coming from the way we handle some xcodebuild flags. The project does indeed seem to build correctly with Swift 4.2. I'm looking into this, but we'll still want to make the two changes I suggested in the review.

**Comment by jessesquires** [comment]
Thanks @clackary !

I've updated the PR with the changes requests.

---

**The output of running:**

```
 ./project_precommit_check ReactiveLists --earliest-compatible-swift-version 4.2
```

```
** CHECK **
--- Validating ReactiveLists Swift version 4.2 compatibility ---
--- Project configured to be compatible with Swift 4.2 ---
--- Checking ReactiveLists platform compatibility with Darwin ---
--- Platform compatibility check succeeded ---
--- Locating swiftc executable ---
$ xcrun -f swiftc
--- Checking installed Swift version ---
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version
--- Version check failed ---
Expected version:
Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
Target: x86_64-apple-darwin17.7.0

Current version:
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.2.0

error: please select Xcode 10.0 (contains Swift 4.2)
```

Looks like we need to set some Xcode project settings for Swift 4.2?

**Comment by clackary** [comment]
Ah, since you're checking something against Swift 4.2, you'd need to have Xcode 10 installed and selected. You appear to have Xcode 10.1 installed, which technically contains Swift 4.2.1. Not a huge deal. I'll start another round of testing.

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by jessesquires** [comment]
Awesome. Thanks @clackary ! 🙌

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
From the [build log](https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/402/artifact/swift-source-compat-suite/FAIL_ReactiveLists_4.2_BuildXcodeWorkspaceScheme_ReactiveLists_generic-platform-iOS.log), it looks like it's failing when trying to run `swiftlint` from a script in the xcodeproj.

```
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/ReactiveLists/build/Build/Intermediates.noindex/ReactiveLists.build/Release-iphoneos/ReactiveLists.build/Script-357B96DD20193EB50000443F.sh: line 2: 26488 Abort trap: 6           ${PODS_ROOT}/SwiftLint/swiftlint
```

I found the corresponding script in ReactiveLists [sources](https://github.com/plangrid/ReactiveLists/blob/d4dc7ab724adcfd342eccebb1f9b9a2c3b95640d/ReactiveLists.xcodeproj/project.pbxproj#L494-L505).

This might be coming from an interaction with the sandbox. Network activity is blocked during build time. Maybe SwiftLint is trying to install during build?

**Comment by jessesquires** [comment]
hey @clackary sorry for the delay here! Just updated this PR.

I think it's ok. But the `project_precommit_check` script still gives me the same error that I mentioned in the comment above. I'm using `Xcode 10.1 (10B61)`

**Comment by clackary** [comment]
@swift-ci please test

**Comment by clackary** [comment]
@jessesquires Sounds good, thanks for the update.

**Comment by clackary** [comment]
The [build log](https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/449/artifact/swift-source-compat-suite/FAIL_ReactiveLists_4.2_BuildXcodeWorkspaceScheme_ReactiveLists_generic-platform-iOS.log) shows a few failures related to `StagedChangeset`...

```
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/ReactiveLists/Pods/DifferenceKit/Sources/StagedChangeset.swift:46:1: error: type 'StagedChangeset<Collection>' does not conform to protocol 'Sequence'
extension StagedChangeset: RandomAccessCollection, RangeReplaceableCollection, MutableCollection {
^
```

**Comment by jessesquires** [comment]
@clackary Ah, that's expected for Xcode 10.2.

I just update to Swift 5, so I'll update the PR for that.

**Comment by jessesquires** [comment]
Or, put another way: it should build with Xcode 10.1, but breaks with Xcode 10.2 (even in 4.2 mode)

**Comment by jessesquires** [comment]
Updated!

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
@swift-ci test

**Comment by clackary** [comment]
The build results there are a few months stale, so I ran a local test against Xcode 11 beta 3, and I expect this to pass now.

**Comment by clackary** [comment]
Build failed because of an issue with SwiftLint...
```
    /bin/sh -c /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/ReactiveLists/build/Build/Intermediates.noindex/ReactiveLists.build/Release-iphoneos/ReactiveLists.build/Script-357B96DD20193EB50000443F.sh
/Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/ReactiveLists/build/Build/Intermediates.noindex/ReactiveLists.build/Release-iphoneos/ReactiveLists.build/Script-357B96DD20193EB50000443F.sh: line 2: 65310 Segmentation fault: 11  ${PODS_ROOT}/SwiftLint/swiftlint
Command PhaseScriptExecution failed with a nonzero exit code

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution SwiftLint /Users/buildnode/jenkins/workspace-private/swift-PR-source-compat-suite-test-macOS/project_cache/ReactiveLists/build/Build/Intermediates.noindex/ReactiveLists.build/Release-iphoneos/ReactiveLists.build/Script-357B96DD20193EB50000443F.sh
(1 failure)
```

**Comment by clackary** [comment]
Oh, this is the same thing we were hitting before?

**Comment by jessesquires** [comment]
cc @anayini @ronaldsmartin -- either of you interested in carrying this PR forward?

**Comment by jessesquires** [comment]
going to close. i don't have time to fix.

cc @anayini @ronaldsmartin
